name: Build and Deploy

on:
  push:
    branches: [ build ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Setup Pages
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Install and Build
        run: bundle exec jekyll build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
